version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load variables from .env file
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "
        if [ ! -d /venv ]; then
          python -m venv /venv;
        fi &&
        /venv/bin/pip install -r requirements.txt &&
        # Wait for PostgreSQL to be ready
        /venv/bin/wait-for-it db:5432 --timeout=30 -- /venv/bin/python manage.py migrate &&
        /venv/bin/python manage.py runserver 0.0.0.0:8000"
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
