services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "
        if [ ! -d /venv ]; then
          python -m venv /venv;
        fi &&

        # Install dependencies in the virtual environment
        /venv/bin/pip install -r requirements.txt &&

        # Wait for PostgreSQL to be ready before running migrations
        /venv/bin/python manage.py wait_for_db &&

        # Apply migrations to the database
        /venv/bin/python manage.py migrate &&

        # Start the Django development server
        /venv/bin/python manage.py runserver 0.0.0.0:8000"

    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge