# Generated by Django 5.1.3 on 2024-12-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
    ]
