name: Checks

on: [push]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: yandex_eats_backend
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: saida0525
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Adjust as per your requirement

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h db -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Set up Django environment variables
        run: |
          echo "DB_NAME=yandex_eats_backend" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=saida0525" >> $GITHUB_ENV
          echo "DB_HOST=db" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py wait_for_db
          python manage.py migrate
          python manage.py test
